// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GenCodeAuto
{
    internal sealed partial class Vsix
    {
        public const string Id = "GenCodeAuto.0734ecf2-ba65-43de-9125-67cb147ab63f";
        public const string Name = "GenCodeAuto";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Company";
        public const string Tags = "";
    }
}
